apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fib-app
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s
    repoURL: >-
      https://github.com/AmeerHossam/Using_GitOps_with_ArgoCD_to_deploy_K8S_app_on_AWS_EKS
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
