version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and test
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            docker build -t sudo1amir/react-test -f ./client/Dockerfile.dev ./client/
      - run:
          name: Push
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t sudo1amir/multi-client-k8s:v1  -f ./client/Dockerfile ./client
            docker build -t sudo1amir/multi-server-k8s:v1  -f ./server/Dockerfile ./server
            docker build -t sudo1amir/multi-worker-k8s:v1  -f ./worker/Dockerfile ./worker

            docker push sudo1amir/multi-client-k8s:v1
            docker push sudo1amir/multi-server-k8s:v1
            docker push sudo1amir/multi-worker-k8s:v1
workflows:
  GitOpsflow:
    jobs:
      - build_and_push